Fix exception java.lang.NoClassDefFoundError: io.opentelemetry.sdk.logs.SdkLogEmitterProviderBuilder (#341)
* Fix exception "java.lang.NoClassDefFoundError: io.opentelemetry.sdk.logs.SdkLogEmitterProviderBuilder"

* Remove unused dependency